/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brandPrimary: '#ff2773',
        brandPrimaryLight: '#ff4d95',
        brandSecondary: '#2b1e70',
        brandSecondaryLight: '#252d9b',
        uiTextPrimary: '#190134',
        uiTextSecondary: '#685879',
        uiTextTertiary: '#b3abbc',
        uiTextSuccess: '#5cc689',
        uiTextError: '#ee7d52',
        uiTextLink: '#252d9b',
        uiTextWhite: '#ffffff',
        uiElementPrimary: '#ffffff',
        uiElementSecondary: '#685879',
        uiElementTertiary: '#b3abbc',
        uiElementSuccess: '#5cc689',
        uiElementError: '#ee7d52',
        uiElementInactive: '#eaeaea',
        uiElementOverlay: '#2b1e70cc',
      },
      boxShadow: {
        shadowBottomLevel1: '0px 2px 10px 0px #1901341f',
        shadowBottomLevel2: '0px 4px 10px 0px #19013429',
        shadowTopLevel1: '0px -2px 10px 0px #1901341f',
        shadowTopLevel2: '0px -4px 10px 0px #19013429',
        borderTopBorder: '0px 1px 0px 0px #eaeaea',
        borderBottomBorder: '0px -1px 0px 0px #eaeaea',
      },
      fontFamily: {
        sfProDisplay: ['SF Pro Display'],
      },
      fontSize: {
        headingH1: [
          '2rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Heavy',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 16,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        headingH2: [
          '1.5rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Heavy',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 12,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        headingH3: [
          '1.25rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Heavy',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 10,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        headingH4: [
          '1rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Heavy',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 8,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        headingH5: [
          '0.875rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Heavy',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 7,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        headingH6: [
          '0.75rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Heavy',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 6,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        uiMainContent: [
          '1rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Regular',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        uiMainContentBold: [
          '1rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        uiSubContent: [
          '0.875rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Regular',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        uiSubContentBold: [
          '0.875rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        uiTinyContent: [
          '0.75rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Regular',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        uiTinyContentBold: [
          '0.75rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        bodyParagraph: [
          '1rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Regular',
            lineHeight: '160%',
            letterSpacing: '0em',
            paragraphSpacing: 16,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        bodyParagraphBold: [
          '1rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Bold',
            lineHeight: '160%',
            letterSpacing: '0em',
            paragraphSpacing: 16,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        bodyLink: [
          '1rem',
          {
            fontFamily: 'SF Pro Display',
            fontWeight: 'Regular',
            lineHeight: '160%',
            letterSpacing: '0em',
            paragraphSpacing: 16,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'underline',
          },
        ],
      },
    },
  },
}
